---
yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'

rules:
  braces: enable
  brackets: enable
  colons: enable
  commas: enable
  comments: disable
  comments-indentation: disable
  document-end: disable
  document-start: disable
  empty-lines: enable
  empty-values: enable
  hyphens: enable
  indentation: enable
  line-length:
    max: 150
    level: warning
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  key-duplicates: enable
  key-ordering: disable
  new-line-at-end-of-file: enable
  new-lines: enable
  octal-values: enable
  quoted-strings: disable
  trailing-spaces: enable
  truthy:
    check-keys: false
    allowed-values: ["true", "false", "yes", "no"]
